export const GET_ALL_CONTACTS_REQUEST = 'GET_ALL_CONTACTS_REQUEST'
export const GET_ALL_CONTACTS_SUCCESS = 'GET_ALL_CONTACTS_SUCCESS'
export const GET_ALL_CONTACTS_FAILURE = 'GET_ALL_CONTACTS_FAILURE'


export const GET_SINGLE_CONTACT_REQUEST = 'GET_SINGLE_CONTACT_REQUEST'
export const GET_SINGLE_CONTACT_SUCCESS = 'GET_SINGLE_CONTACT_SUCCESS'
export const GET_SINGLE_CONTACT_FAILURE = 'GET_SINGLE_CONTACT_FAILURE'


export const UPDATE_CONTACT_REQUEST = 'UPDATE_CONTACT_REQUEST'
export const UPDATE_CONTACT_SUCCESS = 'UPDATE_CONTACT_SUCCESS'
export const UPDATE_CONTACT_FAILURE = 'UPDATE_CONTACT_FAILURE'


