export const GET_ALL_CONTACTS_REQUEST = 'GET_ALL_CONTACTS_REQUEST'
export const GET_ALL_CONTACTS_SUCCESS = 'GET_ALL_CONTACTS_SUCCESS'
export const GET_ALL_CONTACTS_FAILURE = 'GET_ALL_CONTACTS_FAILURE'